var lottery_result_url = "http://lottery.sports.sohu.com/open/";
var lottery_quick_fit = [];

function lottery_add(lotobj){
    lottery_quick_fit.push(lotobj);
}

lottery_add({ area:"全国联销", lottype:"体彩", lotchinesename:"胜负彩(任九)", periodicalnum:"11040", openurl:"sfc.shtml" });
lottery_add({ area:"全国联销", lottype:"体彩", lotchinesename:"六场半全场", periodicalnum:"11045", openurl:"zc6.shtml" });
lottery_add({ area:"全国联销", lottype:"体彩", lotchinesename:"四场进球", periodicalnum:"11051", openurl:"jq4.shtml" });
lottery_add({ area:"全国联销", lottype:"福彩", lotchinesename:"双色球", periodicalnum:"11043", openurl:"ssq.shtml" });
lottery_add({ area:"全国联销", lottype:"体彩", lotchinesename:"超级大乐透", periodicalnum:"11043", openurl:"dlt.shtml" });
lottery_add({ area:"全国联销", lottype:"体彩", lotchinesename:"七星彩", periodicalnum:"11043", openurl:"qxc.shtml" });
lottery_add({ area:"全国联销", lottype:"体彩", lotchinesename:"排列三", periodicalnum:"11100", openurl:"pls.shtml" });
lottery_add({ area:"全国联销", lottype:"体彩", lotchinesename:"排列五", periodicalnum:"11100", openurl:"plw.shtml" });
lottery_add({ area:"全国联销", lottype:"体彩", lotchinesename:"22选5", periodicalnum:"11100", openurl:"eexw.shtml" });
lottery_add({ area:"全国联销", lottype:"福彩", lotchinesename:"福彩3D", periodicalnum:"2011100", openurl:"sd.shtml" });
lottery_add({ area:"全国联销", lottype:"福彩", lotchinesename:"七乐彩", periodicalnum:"11042", openurl:"qlc.shtml" });
lottery_add({ area:"六省联销", lottype:"福彩", lotchinesename:"福彩东方6+1", periodicalnum:"2011043", openurl:"df6j1.shtml" });
lottery_add({ area:"上海", lottype:"福彩", lotchinesename:"福彩天天彩选4", periodicalnum:"4442", openurl:"ttcx4.shtml" });
lottery_add({ area:"广东", lottype:"福彩", lotchinesename:"福彩36选7", periodicalnum:"2086", openurl:"gdslxq.shtml" });
lottery_add({ area:"黑龙江", lottype:"体彩", lotchinesename:"体彩6+1", periodicalnum:"11028", openurl:"hlj6j1.shtml" });
lottery_add({ area:"浙江", lottype:"体彩", lotchinesename:"体彩6+1", periodicalnum:"11043", openurl:"zj6j1.shtml" });
lottery_add({ area:"福建", lottype:"体彩", lotchinesename:"体彩36选7", periodicalnum:"11043", openurl:"fjslxq.shtml" });
lottery_add({ area:"江苏", lottype:"体彩", lotchinesename:"体彩7位数", periodicalnum:"11057", openurl:"js7ws.shtml" });
lottery_add({ area:"全国联销", lottype:"体彩", lotchinesename:"31选7", periodicalnum:"10118", openurl:"syxq.shtml" });
lottery_add({ area:"天津", lottype:"福彩", lotchinesename:"福彩15选5", periodicalnum:"2011100", openurl:"tjswxw.shtml" });
lottery_add({ area:"六省联销", lottype:"福彩", lotchinesename:"福彩15选5", periodicalnum:"2011100", openurl:"hdswxw.shtml" });
lottery_add({ area:"重庆", lottype:"福彩", lotchinesename:"福彩20选5", periodicalnum:"10059", openurl:"cqesxw.shtml" });
lottery_add({ area:"天津", lottype:"体彩", lotchinesename:"体彩6+1", periodicalnum:"11031", openurl:"tjljy.shtml" });
lottery_add({ area:"河北", lottype:"福彩", lotchinesename:"福彩20选5", periodicalnum:"11100", openurl:"hbesxw.shtml" });
lottery_add({ area:"湖北", lottype:"福彩", lotchinesename:"福彩22选5", periodicalnum:"11100", openurl:"cteexw.shtml" });
lottery_add({ area:"山东", lottype:"福彩", lotchinesename:"福彩23选5", periodicalnum:"2011W100", openurl:"sdesxw.shtml" });
lottery_add({ area:"山西", lottype:"福彩", lotchinesename:"福彩21选5", periodicalnum:"2011100", openurl:"sxeyxw.shtml" });
lottery_add({ area:"内蒙古", lottype:"福彩", lotchinesename:"福彩22选5", periodicalnum:"2009174", openurl:"nmeexw.shtml" });
lottery_add({ area:"新疆", lottype:"福彩", lotchinesename:"福彩35选7", periodicalnum:"2011028", openurl:"xjswxq.shtml" });
lottery_add({ area:"新疆", lottype:"福彩", lotchinesename:"福彩25选7", periodicalnum:"2011029", openurl:"xjewxq.shtml" });
lottery_add({ area:"新疆", lottype:"福彩", lotchinesename:"福彩18选7", periodicalnum:"2011028", openurl:"xjsbxq.shtml" });
lottery_add({ area:"新疆", lottype:"福彩", lotchinesename:"福彩偶数10选7", periodicalnum:"2011028", openurl:"xjsxq.shtml" });
lottery_add({ area:"浙江", lottype:"体彩", lotchinesename:"体彩31选7", periodicalnum:"11005", openurl:"zjsyxq.shtml" });
lottery_add({ area:"福建", lottype:"体彩", lotchinesename:"体彩22选5", periodicalnum:"11100", openurl:"fjeexw.shtml" });
lottery_add({ area:"福建", lottype:"体彩", lotchinesename:"体彩31选7", periodicalnum:"11056", openurl:"fjsyxq.shtml" });
lottery_add({ area:"上海", lottype:"福彩", lotchinesename:"福彩15选5", periodicalnum:"2011100", openurl:"shswxw.shtml" });
lottery_add({ area:"江苏", lottype:"福彩", lotchinesename:"福彩15选5", periodicalnum:"2011100", openurl:"jsswxw.shtml" });
lottery_add({ area:"浙江", lottype:"福彩", lotchinesename:"福彩15选5", periodicalnum:"2011100", openurl:"zjswxw.shtml" });
lottery_add({ area:"福建", lottype:"福彩", lotchinesename:"福彩15选5", periodicalnum:"2011100", openurl:"fjswxw.shtml" });
lottery_add({ area:"江西", lottype:"福彩", lotchinesename:"福彩15选5", periodicalnum:"2011100", openurl:"jxswxw.shtml" });
lottery_add({ area:"安徽", lottype:"福彩", lotchinesename:"福彩15选5", periodicalnum:"2011100", openurl:"ahswxw.shtml" });
lottery_add({ area:"北京", lottype:"福彩", lotchinesename:"福彩两步彩", periodicalnum:"2010-148", openurl:"bjebc.shtml" });
lottery_add({ area:"四川", lottype:"福彩", lotchinesename:"福彩22选5", periodicalnum:"11100", openurl:"sceexw.shtml" });
lottery_add({ area:"云南", lottype:"福彩", lotchinesename:"福彩天天乐", periodicalnum:"11100", openurl:"ynttl.shtml" });
lottery_add({ area:"贵州", lottype:"福彩", lotchinesename:"福彩天天乐", periodicalnum:"11100", openurl:"gzttl.shtml" });
lottery_add({ area:"深圳", lottype:"福彩", lotchinesename:"深圳风采", periodicalnum:"2011028", openurl:"szfc.shtml" });
lottery_add({ area:"广西", lottype:"福彩", lotchinesename:"福彩快乐双彩", periodicalnum:"2011100", openurl:"klsc.shtml" });
lottery_add({ area:"湖南", lottype:"福彩", lotchinesename:"福彩22选5", periodicalnum:"2010358", openurl:"hneexw.shtml" });
lottery_add({ area:"安徽", lottype:"福彩", lotchinesename:"福彩25选5", periodicalnum:"11100", openurl:"ahewxw.shtml" });
lottery_add({ area:"黑龙江", lottype:"福彩", lotchinesename:"福彩36选7", periodicalnum:"2011043", openurl:"hljslxq.shtml" });
lottery_add({ area:"江苏", lottype:"体彩", lotchinesename:"体彩5+1", periodicalnum:"10062", openurl:"js5j1.shtml" });
lottery_add({ area:"广东", lottype:"福彩", lotchinesename:"福彩26选5", periodicalnum:"1373", openurl:"gdelxw.shtml" });
lottery_add({ area:"黑龙江", lottype:"福彩", lotchinesename:"福彩P62", periodicalnum:"11100", openurl:"hljp62.shtml" });
lottery_add({ area:"广东", lottype:"体彩", lotchinesename:"体彩36选7", periodicalnum:"11042", openurl:"gdtcslxq.shtml" });
lottery_add({ area:"辽宁", lottype:"福彩", lotchinesename:"福彩35选7", periodicalnum:"2011043", openurl:"lnswxq.shtml" });
lottery_add({ area:"河北", lottype:"福彩", lotchinesename:"福彩好运彩2", periodicalnum:"2011100", openurl:"hbhy2.shtml" });
lottery_add({ area:"河北", lottype:"福彩", lotchinesename:"福彩好运彩3", periodicalnum:"2011100", openurl:"hbhy3.shtml" });
lottery_add({ area:"河北", lottype:"福彩", lotchinesename:"福彩排列5", periodicalnum:"2011043", openurl:"hbplw.shtml" });
lottery_add({ area:"河北", lottype:"福彩", lotchinesename:"福彩排列7", periodicalnum:"2011042", openurl:"hbplq.shtml" });
lottery_add({ area:"黑龙江", lottype:"福彩", lotchinesename:"福彩22选5", periodicalnum:"2011100", openurl:"hljeexw.shtml" });
lottery_add({ area:"河南", lottype:"福彩", lotchinesename:"福彩22选5", periodicalnum:"2011100", openurl:"zyeexw.shtml" });
lottery_add({ area:"浙江", lottype:"体彩", lotchinesename:"体彩20选5", periodicalnum:"11100", openurl:"zjesxw.shtml" });
lottery_add({ area:"广东", lottype:"福彩", lotchinesename:"福彩好彩1", periodicalnum:"2086", openurl:"gdhc1.shtml" });
lottery_add({ area:"北京", lottype:"体彩", lotchinesename:"体彩33选7", periodicalnum:"11100", openurl:"bjssxq.shtml" });
lottery_add({ area:"北京", lottype:"体彩", lotchinesename:"36选7", periodicalnum:"09081", openurl:"bjslxq.shtml" });
